// This file is auto-generated by FlutterFire CLI
// Run: flutterfire configure
// This is a placeholder. Replace with your actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXFTk7mD5GvUOXPA2uOxKaMf6_JwTZgg',
    appId: '1:239318453543:web:97942bb4dafa95fac06d02',
    messagingSenderId: '239318453543',
    projectId: 'fooddelivery-7b43f',
    authDomain: 'fooddelivery-7b43f.firebaseapp.com',
    storageBucket: 'fooddelivery-7b43f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSXFTk7mD5GvUOXPA2uOxKaMf6_JwTZgg',
    appId: '1:239318453543:android:97942bb4dafa95fac06d02',
    messagingSenderId: '239318453543',
    projectId: 'fooddelivery-7b43f',
    storageBucket: 'fooddelivery-7b43f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXFTk7mD5GvUOXPA2uOxKaMf6_JwTZgg',
    appId: '1:239318453543:ios:97942bb4dafa95fac06d02',
    messagingSenderId: '239318453543',
    projectId: 'fooddelivery-7b43f',
    storageBucket: 'fooddelivery-7b43f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSXFTk7mD5GvUOXPA2uOxKaMf6_JwTZgg',
    appId: '1:239318453543:macos:97942bb4dafa95fac06d02',
    messagingSenderId: '239318453543',
    projectId: 'fooddelivery-7b43f',
    storageBucket: 'fooddelivery-7b43f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
