// This file is auto-generated by FlutterFire CLI
// Run: flutterfire configure
// Firebase configuration for Flutter Food Delivery App

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:web:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    authDomain: 'flutter-project-97c3d.firebaseapp.com',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:android:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:ios:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
    iosClientId: '732079814527-ios-client.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:macos:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
    iosClientId: '732079814527-macos-client.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:windows:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA5YeRhCUAPotlCUzjsMujyFeWmtiBAprQ',
    appId: '1:732079814527:linux:97250aef91557799e0cc4a',
    messagingSenderId: '732079814527',
    projectId: 'flutter-project-97c3d',
    storageBucket: 'flutter-project-97c3d.firebasestorage.app',
  );
}